<?php

return [
    // --- GRATUÏTS ---
    'pixel-swords' => false,
    'pixel-bowl' => false,
    'pixel-slime-blue' => false,
    'pixel-slime-red' => false,
    'pixel-ninja' => false,
    'pixel-pirate' => false,
    'pixel-orb' => false,
    'pixel-soccer' => false,
    'pixel-hero' => false,
    'pixel-heart' => false,
    'pixel-ghost' => false,
    'pixel-invader' => false,
    'pixel-shroom' => false,
    'pixel-gem' => false,
    'pixel-ring' => false,
    'pixel-shield' => false,
    'pixel-potion' => false,
    'pixel-scroll' => false,
    'pixel-cat' => false,
    'pixel-fox' => false,
    'pixel-panda' => false,
    'pixel-rocket' => false,
    'pixel-burger' => false,
    'pixel-headset' => false,

    // --- PREMIUM ---
    'pixel-crown' => true,
    'pixel-gamepad' => true,
    'pixel-skull' => true,
    'pixel-mask' => true,
    'pixel-tiara' => true,
    'pixel-mecha' => true,
    'pixel-titan' => true,
    'pixel-watch' => true,
    'pixel-wizard' => true,
    'pixel-chest' => true,
    'pixel-rankball' => true,
    'pixel-pickaxe' => true,
    'pixel-star' => true,
    'pixel-helmet' => true,
    'pixel-axe' => true,
    'pixel-castle' => true,
    'pixel-lion' => true,
    'pixel-wolf' => true,
    'pixel-dragon' => true,
    'pixel-bolt' => true,
];